name: Update Repository

on:
  push:
    branches:
      - main
    paths:
      - 'debians/**'
      - 'assets/repo/repo.conf'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install required packages
      run: |
        sudo apt update
        sudo apt install -y apt-utils wget xz-utils zstd

    - name: Run script
      run: |
        rm -f Packages Packages.xz Packages.gz Packages.bz2 Packages.zst Release 2> /dev/null
        apt-ftparchive packages ./debians > Packages
        gzip -c9 Packages > Packages.gz
        xz -c9 Packages > Packages.xz
        zstd -c19 Packages > Packages.zst
        bzip2 -c9 Packages > Packages.bz2
        apt-ftparchive release -c ./assets/repo/repo.conf . > Release
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: updates packages
